<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require '../../vendor/autoload.php'; // Path to the autoload.php file generated by Composer

function sendVerificationEmail($recipientEmail, $verificationCode, $userType) {
    global $conn; // Ensure the database connection is accessible

    // Retrieve user's first name based on the email
    $stmt = $conn->prepare("SELECT req_fname FROM request_signup_tbl WHERE req_email = ?");
    $stmt->bind_param('s', $recipientEmail);
    $stmt->execute();
    $stmt->store_result();

    $first_name = 'User'; // Default name if not found

    if ($stmt->num_rows > 0) {
        $stmt->bind_result($first_name);
        $stmt->fetch();
    }

    $mail = new PHPMailer(true);
    try {
        // Server settings
        $mail->isSMTP();
        $mail->Host = 'smtp.gmail.com';
        $mail->SMTPAuth = true;
        $mail->Username = 'kyuuichi12@gmail.com'; // SMTP username
        $mail->Password = 'cayj eaug pwcx xqvn'; // SMTP password or App Password
        $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
        $mail->Port = 587;

        // Recipients
        $mail->setFrom('kyuuichi12@gmail.com', 'SPORTS MANAGEMENT SYSTEM'); // Sender's email
        $mail->addAddress($recipientEmail);

        // Generate verification link
        $verificationLink = "http://localhost/sportManagementSystem/verifyEmail.php?email=" . urlencode($recipientEmail) . "&code=" . urlencode($verificationCode) . "&type=" . urlencode($userType);

        // Email content
        $mail->isHTML(true);
        $mail->Subject = 'Email Verification Code';
        $mail->Body = '
            <html>
            <head>
                <style>
                    .email-container {
                        font-family: Arial, sans-serif;
                        padding: 20px;
                        background-color: #dcdcdc;
                        color: #333;
                        border: 1px solid #ddd;
                        border-radius: 5px;
                        max-width: 600px;
                        margin: auto;
                    }
                    .email-header {
                        background-color: #3c3c3c;
                        color: #fff;
                        padding: 10px;
                        text-align: center;
                        border-radius: 5px 5px 0 0;
                    }
                    .email-body {
                        padding: 20px;
                    }
                    .email-footer {
                        padding: 10px;
                        text-align: center;
                        font-size: 12px;
                        color: #777;
                    }
                    .btn {
                        background-color: #4CAF50;
                        color: #ffffff;
                        padding: 10px 20px;
                        text-decoration: none;
                        border-radius: 5px;
                        display: inline-block;
                        margin-top: 20px;
                    }
                    a {
                        color: #ffffff !important;
                        text-decoration: none;
                    }
                    .btn:hover {
                        background-color: #45a049;
                    }
                </style>
            </head>
            <body>
                <div class="email-container">
                    <div class="email-header">
                        <h2>Email Verification</h2>
                    </div>
                    <div class="email-body">
                        <p>Hey ' . htmlspecialchars($first_name) . ',</p>
                        <p>Welcome to the Sports Management System! To complete your registration, please use the following verification code:</p>
                        <center><h1>' . htmlspecialchars($verificationCode) . '</h1></center>
                        <p>You can verify your email by clicking the button below:</p>
                        <center><a class="btn" href="' . htmlspecialchars($verificationLink) . '">Verify Email</a></center>
                        <p>If you did not register for an account, please ignore this email or contact support if you have any questions.</p>
                        <p>Thanks,</p>
                        <p>The Sports Management System Team</p>
                    </div>
                    <div class="email-footer">
                        <p>&copy; ' . date('Y') . ' Sports Management System. All rights reserved.</p>
                    </div>
                </div>
            </body>
            </html>
        ';

        $mail->send();
        return true;
    } catch (Exception $e) {
        error_log("Message could not be sent. Mailer Error: {$mail->ErrorInfo}");
        return false;
    }
}

?>
