<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require '../../vendor/autoload.php'; // Path to the autoload.php file generated by Composer

function sendVerificationEmail($recipientEmail, $verificationCode, $userType) {
    $mail = new PHPMailer(true);
    try {
        // Server settings
        $mail->isSMTP();
        $mail->Host = 'smtp.gmail.com';
        $mail->SMTPAuth = true;
        $mail->Username = 'kyuuichi12@gmail.com'; // SMTP username
        $mail->Password = 'cayj eaug pwcx xqvn'; // SMTP password or App Password
        $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
        $mail->Port = 587;

        // Recipients
        $mail->setFrom('kyuuichi12@gmail.com', 'SPORTS MANAGEMENT SYSTEM'); // Sender's email
        $mail->addAddress($recipientEmail);

        // Generate verification link
        $verificationLink = "http://localhost/sportSystem/verifyEmail.php?email=" . urlencode($recipientEmail) . "&code=" . urlencode($verificationCode) . "&type=" . urlencode($userType);

        // Content
        $mail->isHTML(true);
        $mail->Subject = 'Email Verification Code';
        $mail->Body    = "Please enter the following code to verify your email: <b>$verificationCode</b><br><br>
                          Or click the link below to verify your email:<br>
                          <a href='$verificationLink'>$verificationLink</a>";

        $mail->send();
        return true;
    } catch (Exception $e) {
        error_log("Message could not be sent. Mailer Error: {$mail->ErrorInfo}");
        return false;
    }
}
?>
